// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "fe615ac7-ac63-4183-a5aa-0c8ae0101d6a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575627112);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575627232);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575630232);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575626872);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575626752);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575626992);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575627472);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575627352);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575626602);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{417714a5-f886-4659-9f62-47e203607721}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575619200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575630291994");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575632116994");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575630212734");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575633812734");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575626605");
user_pref("browser.slowStartup.averageTime", 7481);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575626609021");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "3e4469eaa92d460c83708fd5b0b35154");
user_pref("extensions.blocklist.lastModified", "Wed, 04 Dec 2019 18:51:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575627117);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"19b2a723-fd0b-423e-9c5e-a4a4d813e255\",\"screenshots@mozilla.org\":\"62c2a9d9-03d7-4433-bb1d-7fc8621f6f60\",\"webcompat-reporter@mozilla.org\":\"60e92416-bfdb-4197-8015-bb5649f14b36\",\"webcompat@mozilla.org\":\"23a8a69f-0e9b-4c98-9ad2-2ae4401ad7fa\"}");
user_pref("idle.lastDailyNotification", 1575626943);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575626690);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575626684);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575626943);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "d63c2863-a110-4792-a32a-219da2b28040");
user_pref("security.sandbox.plugin.tempDirSuffix", "25bcfe3d-c1c0-4f04-bbaf-b69c40af43de");
user_pref("services.blocklist.addons.checked", 1575629067);
user_pref("services.blocklist.gfx.checked", 1575626991);
user_pref("services.blocklist.onecrl.checked", 1575626991);
user_pref("services.blocklist.pinning.checked", 1575626991);
user_pref("services.blocklist.plugins.checked", 1575626991);
user_pref("services.settings.clock_skew_seconds", -2);
user_pref("services.settings.last_etag", "\"1575628796682\"");
user_pref("services.settings.last_update_seconds", 1575629067);
user_pref("services.settings.main.language-dictionaries.last_check", 1575626991);
user_pref("services.settings.main.sites-classification.last_check", 1575626991);
user_pref("services.settings.main.tippytop.last_check", 1575626991);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575626943);
user_pref("toolkit.startup.last_success", 1575626597);
user_pref("toolkit.telemetry.cachedClientID", "43b2b374-36ad-43b2-873e-d383e1989941");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
